influxDB:
  host: "http://192.168.1.114"
  port: "8086"
  token: "mzf--------Wg=="
  bucket: "reef-mon"
  org: "reef-mon"

monitors:
  monitor:
    name: "WaterLow"
    measurement: "water_low"
    field: "status"
    interval: 1
    type:
      name: "gpio_switch"
      pin: 22
