influxDB:
  host: "http://192.168.1.124"
  port: "8086"
  token: "O="
  bucket: "reef-mon"
  org: "reef-mon"

monitors:
  monitor:
    name: "WaterLow"
    measurement: "water_low"
    field: "status"
    interval: 10
    type:
      name: "gpio_switch"
      pin: 22
      active_low: true
    influx:
      bucket: "reef-mon-water-level"
